export const SPREADSHEET_URL =
  'https://docs.google.com/spreadsheets/d/1hLO5IbrC6MIwYvqrRS1V_YYHpaQq9Lcvau07jpRezz8/edit#gid=0;'; // Electronic Monitoring Request
// 'https://docs.google.com/spreadsheets/d/1wyPjcdA8DVUeCbyYCanyOaBxcv_YlJK8WIrPnQ0JeOk/edit#gid=518849693'; // Copy of BALT Data 11/2/21
// 'https://docs.google.com/spreadsheets/d/1GWh-B_IMmvNniy2p82CKQ9X-eepwx70BG50xCM5r2bo/edit#gid=1404273585';

export const [
  SUBMITTED_ON_INDEX_ON_INTAKE_FORM,
  CLIENT_NAME_INDEX_ON_INTAKE_FORM,
] = [...Array(2).keys()];

// IMPORTANT: If you edit the intake form, you'll also need to edit
// the formatIndividualClientData function in the sheets.js file
export const [
  SUBMITTED_ON_INDEX_ON_INTAKE_SHEET,
  UNUSED_CLIENT_NAME_INDEX_ON_INTAKE_SHEET, // for some reason this column isn't used anymore
  EMAIL_INDEX_ON_INTAKE_SHEET,
  CLIENTS_PHONE_NUMBER_INDEX_ON_INTAKE_SHEET,
  BEST_WAY_TO_CONTACT_CLIENT_INDEX_ON_INTAKE_SHEET,
  CLIENTS_DATE_OF_BIRTH_INDEX_ON_INTAKE_SHEET,
  CLIENTS_NEXT_COURT_DATE_INDEX_ON_INTAKE_SHEET,
  CASE_NUMBER_INDEX_ON_INTAKE_SHEET,
  ATTORNEYS_NAME_INDEX_ON_INTAKE_SHEET,
  IS_REPRESENTATION_FROM_PUBLIC_DEFENDERS_OFFICE_INDEX_ON_INTAKE_SHEET,
  HOME_DETENTION_COMPANY_INDEX_ON_INTAKE_SHEET,
  CLIENT_HOOK_UP_DATE_INDEX_ON_INTAKE_SHEET,
  KNOWN_DRUG_ISSUES_INDEX_ON_INTAKE_SHEET,
  HEALTH_ISSUES_INDEX_ON_INTAKE_SHEET,
  IMPORTANT_CLIENT_DETAILS_INDEX_ON_INTAKE_SHEET,
  INFO_FOR_SOMEONE_FILLING_OUT_ON_BEHALF_OF_CLIENT_INDEX_ON_INTAKE_SHEET,
  CONFIRMED_PICKUP_INDEX_ON_INTAKE_SHEET,
  RESCHEULED_COURT_DATE_INDEX_ON_INTAKE_SHEET,
  NOTES_INDEX_ON_INTAKE_SHEET,
  CLIENT_NAME_INDEX_ON_INTAKE_SHEET,
] = [...Array(19).keys()];

export const [
  INTAKE_FORM_SHEET_INDEX,
  CLIENT_SHEET_INDEX,
  PAYMENT_BREAKDOWN_SHEET_INDEX,
  PAYMENT_OVERVIEW_SHEET_INDEX,
] = [...Array(4).keys()];

export const [
  CLIENT_ID_INDEX_ON_CLIENT_SHEET,
  SUBMITTED_ON_INDEX_ON_CLIENT_SHEET,
  CLIENT_NAME_INDEX_ON_CLIENT_SHEET,
  TOTAL_PAID_INDEX_ON_CLIENT_SHEET,
  NUMBER_OF_DAYS_OWED_INDEX_ON_CLIENT_SHEET,
  PAYMENT_PICKUP_DATE_INDEX_ON_CLIENT_SHEET,
  PAID_THROUGH_DATE_INDEX_ON_CLIENT_SHEET,
  REIMBURSEMENT_OWED_INDEX_ON_CLIENT_SHEET,
  REIMBURSEMENT_USED_INDEX_ON_CLIENT_SHEET,
  TERMINATION_DATE_INDEX_ON_CLIENT_SHEET,
  EMAIL_INDEX_ON_CLIENT_SHEET,
  CLIENTS_PHONE_NUMBER_INDEX_ON_CLIENT_SHEET,
  BEST_WAY_TO_CONTACT_CLIENT_INDEX_ON_CLIENT_SHEET,
  CLIENTS_DATE_OF_BIRTH_INDEX_ON_CLIENT_SHEET,
  CLIENTS_NEXT_COURT_DATE_INDEX_ON_CLIENT_SHEET,
  CASE_NUMBER_INDEX_ON_CLIENT_SHEET,
  ATTORNEYS_NAME_INDEX_ON_CLIENT_SHEET,
  IS_REPRESENTATION_FROM_PUBLIC_DEFENDERS_OFFICE_INDEX_ON_CLIENT_SHEET,
  HOME_DETENTION_COMPANY_INDEX_ON_CLIENT_SHEET,
  CLIENT_HOOK_UP_DATE_INDEX_ON_CLIENT_SHEET,
  KNOWN_DRUG_ISSUES_INDEX_ON_CLIENT_SHEET,
  HEALTH_ISSUES_INDEX_ON_CLIENT_SHEET,
  IMPORTANT_CLIENT_DETAILS_INDEX_ON_CLIENT_SHEET,
  INFO_FOR_SOMEONE_FILLING_OUT_ON_BEHALF_OF_CLIENT_INDEX_ON_CLIENT_SHEET,
  CONFIRMED_PICKUP_INDEX_ON_CLIENT_SHEET,
  RESCHEULED_COURT_DATE_INDEX_ON_CLIENT_SHEET,
  NOTES_INDEX_ON_CLIENT_SHEET,
] = [...Array(27).keys()];

export const dateFields = [
  RESCHEULED_COURT_DATE_INDEX_ON_CLIENT_SHEET,
  PAYMENT_PICKUP_DATE_INDEX_ON_CLIENT_SHEET,
  CLIENT_HOOK_UP_DATE_INDEX_ON_CLIENT_SHEET,
  CLIENTS_NEXT_COURT_DATE_INDEX_ON_CLIENT_SHEET,
  CLIENTS_DATE_OF_BIRTH_INDEX_ON_CLIENT_SHEET,
  TERMINATION_DATE_INDEX_ON_CLIENT_SHEET,
  PAID_THROUGH_DATE_INDEX_ON_CLIENT_SHEET,
  SUBMITTED_ON_INDEX_ON_CLIENT_SHEET,
];

export const [
  CLIENT_ID_INDEX_ON_PAYMENT_SHEET,
  PAYMENT_ID_INDEX_ON_PAYMENT_SHEET,
  START_DATE_INDEX_ON_PAYMENT_SHEET,
  END_DATE_INDEX_ON_PAYMENT_SHEET,
  REIMBURSEMENT_INDEX_ON_PAYMENT_SHEET,
  NOTES_INDEX_ON_PAYMENT_SHEET,
] = [...Array(6).keys()];

export const [
  PAYMENT_ID_INDEX_ON_PAYMENT_OVERVIEW_SHEET,
  RATE_INDEX_ON_PAYMENT_OVERVIEW_SHEET,
  DATE_PAID_INDEX_ON_PAYMENT_OVERVIEW_SHEET,
  PAID_BY_INDEX_ON_PAYMENT_OVERVIEW_SHEET,
  COMPANY_NAME_INDEX_ON_PAYMENT_OVERVIEW_SHEET,
  TOTAL_INDEX_ON_PAYMENT_OVERVIEW_SHEET,
] = [...Array(6).keys()];
