export const [
  SUBMITTED_ON_INDEX_ON_INTAKE_FORM,
  CLIENT_NAME_INDEX_ON_INTAKE_FORM,
] = [...Array(2).keys()];

export const [
  CLIENT_ID_INDEX_ON_CLIENT_SHEET,
  SUBMITTED_ON_INDEX_ON_CLIENT_SHEET,
  CLIENT_NAME_INDEX_ON_CLIENT_SHEET,
  TOTAL_PAID_INDEX_ON_CLIENT_SHEET,
  NUMBER_OF_DAYS_OWED_INDEX_ON_CLIENT_SHEET,
  PAYMENT_PICKUP_DATE_INDEX_ON_CLIENT_SHEET,
  PAID_THROUGH_DATE_INDEX_ON_CLIENT_SHEET,
  REIMBURSEMENT_OWED_INDEX_ON_CLIENT_SHEET,
  REIMBURSEMENT_USED_INDEX_ON_CLIENT_SHEET,
  TERMINATION_DATE_INDEX_ON_CLIENT_SHEET,
  EMAIL_INDEX_ON_CLIENT_SHEET,
  CLIENTS_PHONE_NUMBER_INDEX_ON_CLIENT_SHEET,
  BEST_WAY_TO_CONTACT_CLIENT_INDEX_ON_CLIENT_SHEET,
  CLIENTS_DATE_OF_BIRTH_INDEX_ON_CLIENT_SHEET,
  CLIENTS_NEXT_COURT_DATE_INDEX_ON_CLIENT_SHEET,
  CASE_NUMBER_INDEX_ON_CLIENT_SHEET,
  ATTORNEYS_NAME_INDEX_ON_CLIENT_SHEET,
  IS_REPRESENTATION_FROM_PUBLIC_DEFENDERS_OFFICE_INDEX_ON_CLIENT_SHEET,
  HOME_DETENTION_COMPANY_INDEX_ON_CLIENT_SHEET,
  CLIENT_HOOK_UP_DATE_INDEX_ON_CLIENT_SHEET,
  KNOWN_DRUG_ISSUES_INDEX_ON_CLIENT_SHEET,
  HEALTH_ISSUES_INDEX_ON_CLIENT_SHEET,
  IMPORTANT_CLIENT_DETAILS_INDEX_ON_CLIENT_SHEET,
  INFO_FOR_SOMEONE_FILLING_OUT_ON_BEHALF_OF_CLIENT_INDEX_ON_CLIENT_SHEET,
  CONFIRMED_PICKUP_INDEX_ON_CLIENT_SHEET,
  RESCHEULED_COURT_DATE_INDEX_ON_CLIENT_SHEET,
  NOTES_INDEX_ON_CLIENT_SHEET,
] = [...Array(27).keys()];

export const dateFields = [
  RESCHEULED_COURT_DATE_INDEX_ON_CLIENT_SHEET,
  PAYMENT_PICKUP_DATE_INDEX_ON_CLIENT_SHEET,
  CLIENT_HOOK_UP_DATE_INDEX_ON_CLIENT_SHEET,
  CLIENTS_NEXT_COURT_DATE_INDEX_ON_CLIENT_SHEET,
  CLIENTS_DATE_OF_BIRTH_INDEX_ON_CLIENT_SHEET,
  TERMINATION_DATE_INDEX_ON_CLIENT_SHEET,
  PAID_THROUGH_DATE_INDEX_ON_CLIENT_SHEET,
  SUBMITTED_ON_INDEX_ON_CLIENT_SHEET,
];

export const [
  CLIENT_ID_INDEX_ON_PAYMENT_SHEET,
  PAYMENT_ID_INDEX_ON_PAYMENT_SHEET,
  START_DATE_INDEX_ON_PAYMENT_SHEET,
  END_DATE_INDEX_ON_PAYMENT_SHEET,
  REIMBURSEMENT_INDEX_ON_PAYMENT_SHEET,
  NOTES_INDEX_ON_PAYMENT_SHEET,
] = [...Array(6).keys()];

export const [
  PAYMENT_ID_INDEX_ON_PAYMENT_OVERVIEW_SHEET,
  RATE_INDEX_ON_PAYMENT_OVERVIEW_SHEET,
  DATE_PAID_INDEX_ON_PAYMENT_OVERVIEW_SHEET,
  PAID_BY_INDEX_ON_PAYMENT_OVERVIEW_SHEET,
  COMPANY_NAME_INDEX_ON_PAYMENT_OVERVIEW_SHEET,
  TOTAL_INDEX_ON_PAYMENT_OVERVIEW_SHEET,
] = [...Array(6).keys()];
